import {Request} from './request';

export const REQUESTS: Request[] = [
  {
    id: 1,
    date: "2019-09-27 05:57",
    name:"Tom Chris",
    university:"UCL",
    type:"Lecture",
    topic:"Machine Learning",
    state:"pending",
  },
  {
    id: 2,
    date: "2019-09-27 05:57",
    name:"Tony Bruce",
    university:"UCL",
    type:"Lecture",
    topic:"Machine Learning",
    state:"pending",
  },
  {
    id: 3,
    date: "2019-09-27 05:57",
    name:"Kevin Paul",
    university:"KCL",
    type:"Lecture",
    topic:"Artificial Intellegence",
    state:"Rejected",
  },
  {
    id: 4,
    date: "2019-09-27 05:57",
    name:"Stephin William	",
    university:"UCL",
    type:"Lecture",
    topic:"Carrer Service",
    state:"pending",
  },
  {
    id: 5,
    date: "2019-09-27 05:57",
    name:"Yanke Zhang	",
    university:"UCL",
    type:"Student Support",
    topic:"Student Support",
    state:"pending",
  },
  {
    id: 6,
    date: "2019-09-27 05:57",
    name:"Shinya Takayama	",
    university:"UCL",
    type:"Lecture",
    topic:"Machine Learning",
    state:"pending",
  },
  {
    id: 7,
    date: "2019-09-27 05:57",
    name:"Absha Abdusalem	",
    university:"UCL",
    type:"Lecture",
    topic:"CS course showcase	",
    state:"pending",
  },
  {
    id: 8,
    date: "2019-09-27 05:57",
    name:"Jimmy James	",
    university:"UCL",
    type:"Lecture",
    topic:"Machine Learning",
    state:"pending",
  },
];
