import {Staff} from './staff';

export const STAFFS: Staff[] = [
  {
    id: 1,
    name:"Tom Chris",
    university: 'SOAS',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 2,
    name:"Tony Bruce	",
    university: 'University College London',
    job_title:"Department Leader",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 3,
    name:"Kevin Paul",
    university: 'Kings\'s College',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 4,
    name:"Stephin William",
    university: 'Imperial College London',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 5,
    name:"Yanke Zhang",
    university: 'University College London',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 6,
    name:"Shinya Takayama",
    university: 'University College London',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 7,
    name:"Jimmy Lee",
    university: 'University College London',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 8,
    name:"Evans Hunter",
    university: 'Cambridge University',
    job_title:"Head master",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  },
  {
    id: 9,
    name:"Julie Parker",
    university: 'University College London',
    job_title:"Professor",
    email:"example@uni.co.uk",
    lecture: 100,
    support: 10,
    hachathon: 10,
    other: 2,
    total: 122,
  }
];
